apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deploy.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.deploy.name}}
  template:
    metadata:
      labels:
        app: {{.Values.deploy.name}}
    spec:
      containers:
        - name: {{.Values.deploy.name}}
          image: "stevegriffith/clippyfunc:{{.Values.deploy.imageTag}}"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: ".5"
            limits:
              memory: "1024Mi"
              cpu: "2.0"
          env:
          ports:
          - containerPort: {{.Values.deploy.containerPort}}
            protocol: TCP
      restartPolicy: Always        